version: "3.8"
services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - development
  db:
    image: postgres:10
    env_file: .env
    ports:
      - 5455:5432
    networks:
      - development
networks:
  development:
    driver: bridge